#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"

if [ $# -eq 0 ]
  then
    echo "Error: Must supply target to deploy to.";
elif [ $1 == "prod" ]
  then
    if [[ -z $2 ]]
      then
        echo "Running dry-run"
        rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ../ craig@craigsc.com:/var/www/craigsc.com
    elif [ $2 == "go" ]
      then
        echo "Running actual deploy"
        rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ../ craig@craigsc.com:/var/www/craigsc.com
    else
      echo "Error: Unknown deploy target provided.";
    fi
fi
